### ISSUE TITLE
Unable to deploy contract with Trezor - trezorlib attribute error

### ISSUE THREAD

**Issue by merc1er** [ApeWorX/ape-trezor#18]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.4.0

$ ape plugins list
Installed Plugins:
  template    0.4.0
  trezor      0.4.0
  vyper       0.4.0
  infura      0.4.0
```

* Python Version: 3.10.4
* OS: macOS 12.5

### What went wrong?

When deploying the default ERC20 token template with a Trezor account, I am getting:

```
❯ ape run scripts/deploy.py --network ethereum:ropsten:infura
0. local
1. trezor
2. trezor-ropsten

Select an account: 2
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.10.4/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ape_run/_cli.py", line 23, in invoke
    return super().invoke(ctx)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ape/cli/commands.py", line 18, in invoke
    super().invoke(ctx)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ape_run/_cli.py", line 73, in call
    ns["main"]()  # Execute the script
  File "/Users/me/Desktop/token/scripts/deploy.py", line 7, in main
    account.deploy(project.Token)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ape/api/accounts.py", line 172, in deploy
    receipt = self.call(txn)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ape/api/accounts.py", line 108, in call
    txn.signature = self.sign_transaction(txn)
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ape_trezor/accounts.py", line 94, in sign_transaction
    signed_txn = self.client.sign_transaction(txn.dict())
  File "/Users/me/.pyenv/versions/3.10.4/lib/python3.10/site-packages/ape_trezor/client.py", line 114, in sign_transaction
    if isinstance(tx_type, TransactionType.STATIC):
AttributeError: type object 'TransactionType' has no attribute 'STATIC'
```

### How can it be fixed?

It seems the Trezor lib is not used properly as `TransactionType` does not have the STATIC attribute: https://github.com/trezor/trezor-firmware/blob/459270ef3ffe691a2e017aa8d6ccdd7178fefff9/python/src/trezorlib/messages.py#L1673

Note that I looked at the latest version or trezorlib, this might have been removed.

**Comment by unparalleled-js** [comment]
The bug is actually because of us I think.
We need to use `from ape_ethereum import TransactionType` instead of the trezorlib class.

**Comment by merc1er** [comment]
Thanks.

Will you be issuing a patch or do you want me to try to work on this?

**Comment by unparalleled-js** [comment]
> Thanks.

You are welcome!
 
> Will you be issuing a patch or do you want me to try to work on this?

@NotPeopling2day and I are looking this. We are going to get this patched and add some more testing to this plugin.

**Comment by unparalleled-js** [comment]
> Will you be issuing a patch or do you want me to try to work on this?

You are welcome to get a PR going though! Maybe we can all collab.

**Comment by merc1er** [comment]
> You are welcome to get a PR going though! Maybe we can all collab.

Seems like there's already a PR for it. But if there's anything you want me to do (test it maybe?) let me know.

**Comment by merc1er** [comment]
Seems like PR #19 was not merged. Is there anything I can do to help on this @unparalleled-js @NotPeopling2day?

**Comment by unparalleled-js** [comment]
> Seems like PR #19 was not merged. Is there anything I can do to help on this @unparalleled-js @NotPeopling2day?

@NotPeopling2day Are you focused on other tasks? Let's let @merc1er assist.
I like #19 started off more focused on EIP-712 which probably should be a separate PR. So I propose @NotPeopling2day can complete that work and @merc1er can look at this if they want.

Ping me on Telegram for assistance, I can also make time for this. I would really like to see this patched soon!
telegram: `@Antazoey`
