### ISSUE TITLE
`Forbidden key path` when using default derivation path

### ISSUE THREAD

**Issue by merc1er** [ApeWorX/ape-trezor#24]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.5.1

$ ape plugins list
Installed Plugins:
  trezor      0.5.0
  optimism    0.5.0a1
  vyper       0.5.0
  bsc         0.5.0a1
```

* Python Version: 3.10.6
* OS: macOS

### What went wrong?

After entering my PIN, I am getting the error:

```shell
trezorlib.exceptions.TrezorFailure: DataError: Forbidden key path
```

<details>

<summary>Full traceback.</summary>

```shell
The layout is:

    7 8 9        e r t
    4 5 6  -or-  d f g
    1 2 3        c v b
Please enter current PIN: 
Traceback (most recent call last):
  File "/Users/cloudfloat/.pyenv/versions/ape/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/ape_run/_cli.py", line 23, in invoke
    return super().invoke(ctx)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/ape/cli/commands.py", line 18, in invoke
    super().invoke(ctx)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/ape_run/_cli.py", line 73, in call
    ns["main"]()  # Execute the script
  File "/Users/cloudfloat/Documents/cloud-aud/scripts/deploy.py", line 14, in main
    account.deploy(project.Token)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/ape/api/accounts.py", line 174, in deploy
    receipt = self.call(txn)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/ape/api/accounts.py", line 108, in call
    txn.signature = self.sign_transaction(txn)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/ape_trezor/accounts.py", line 94, in sign_transaction
    signed_txn = self.client.sign_transaction(txn.dict())
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/ape_trezor/client.py", line 129, in sign_transaction
    tuple_reply = ethereum.sign_tx_eip1559(
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/trezor-0.13.3-py3.10.egg/trezorlib/tools.py", line 288, in wrapped_f
    return f(client, *args, **kwargs)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/trezor-0.13.3-py3.10.egg/trezorlib/ethereum.py", line 251, in sign_tx_eip1559
    response = client.call(msg)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/trezor-0.13.3-py3.10.egg/trezorlib/tools.py", line 288, in wrapped_f
    return f(client, *args, **kwargs)
  File "/Users/cloudfloat/.pyenv/versions/ape/lib/python3.10/site-packages/trezor-0.13.3-py3.10.egg/trezorlib/client.py", line 258, in call
    raise exceptions.TrezorFailure(resp)
trezorlib.exceptions.TrezorFailure: DataError: Forbidden key path
```

</details>

I believe this is due to using a different derivation path (`"m/44'/1'/0'/0"`) from the default one, because I am able to deploy the same contract just fine with the custom path of `"m/44'/1'/0'/0"`.

Is this a limitation from `trezorlib`? If so, maybe it would be best to force `"m/44'/1'/0'/0"` as the only possible derivation path.

**Comment by merc1er** [comment]
Seems like that was answered here: https://github.com/trezor/trezor-firmware/issues/1336#issuecomment-720126545.

In this case I suggest the derivation path defaults to `m/44'/1'/0'/0` when adding trezor accounts via `ape trezor add`.
